### PR TITLE
Added Vue.js Description

### PR DESCRIPTION
**Pull request by tom-tielebein**
Added the Vue.js description with three links.

### CODE REVIEW

**Comment by btopro** [comment]
@AbstractFeel can you please make the links a bulleted list? It'll help w/ organizing the document as everyone is adding them. Other then that looks like exactly what we're looking for!

**Comment by btopro** [comment]
perfect! thank you for the change

**Comment by btopro** [comment]
#47

**Comment by tom-tielebein** [comment]
no problem, thank you

**Pull request merged**
